export default {
  ADD_ITEM: "ADD_ITEM",
  GET_HOMESCREEN_ITEMS: "GET_HOMESCREEN_ITEMS",
  SET_HOMESCREEN_ITEMS: "SET_HOMESCREEN_ITEMS",
  GET_CATEGORY_ITEMS: "GET_CATEGORY_ITEMS",
  SET_CATEGORY_ITEMS: "SET_CATEGORY_ITEMS"
};
